#!/usr/bin/env python3
"""Render the accepted ARCI sensitivity summary as a deterministic Markdown table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


EXPECTED_SCHEMA = "sns.arci-synthetic-sensitivity.v1"


def _number(value: Any, field: str) -> int | float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{field} must be numeric")
    return value


def render_table(payload: dict[str, Any]) -> str:
    if payload.get("schema") != EXPECTED_SCHEMA:
        raise ValueError(f"expected schema {EXPECTED_SCHEMA}")
    if payload.get("synthetic") is not True:
        raise ValueError("ARCI public table accepts synthetic evidence only")

    baseline = payload.get("baseline")
    sensitivity = payload.get("sensitivity")
    next_measurement = payload.get("next_measurement")
    if not isinstance(baseline, dict) or not isinstance(sensitivity, dict) or not isinstance(next_measurement, dict):
        raise ValueError("baseline, sensitivity, and next_measurement objects are required")

    score = _number(baseline.get("score"), "baseline.score")
    confidence = _number(baseline.get("confidence"), "baseline.confidence")
    adjusted = _number(baseline.get("confidence_adjusted_score"), "baseline.confidence_adjusted_score")
    scenarios = _number(sensitivity.get("scenario_count"), "sensitivity.scenario_count")
    score_range = sensitivity.get("confidence_adjusted_score_range")
    if not isinstance(score_range, list) or len(score_range) != 2:
        raise ValueError("sensitivity.confidence_adjusted_score_range must contain two values")
    low = _number(score_range[0], "sensitivity.confidence_adjusted_score_range[0]")
    high = _number(score_range[1], "sensitivity.confidence_adjusted_score_range[1]")
    reversal = sensitivity.get("major_grade_reversal")
    if not isinstance(reversal, bool):
        raise ValueError("sensitivity.major_grade_reversal must be boolean")
    grade = baseline.get("grade")
    dimension = next_measurement.get("dimension")
    if not isinstance(grade, str) or not isinstance(dimension, str):
        raise ValueError("baseline.grade and next_measurement.dimension must be strings")

    rows = [
        ("Baseline score", f"{score:.7g}"),
        ("Evidence confidence", f"{confidence:.7g}"),
        ("Confidence-adjusted score", f"{adjusted:.7g}"),
        ("Sensitivity scenarios", str(scenarios)),
        ("Adjusted-score range", f"{low:.7g}–{high:.7g}"),
        ("Major grade reversal", "yes" if reversal else "no"),
        ("Evidence grade", grade),
        ("Next-measurement dimension", f"`{dimension}`"),
    ]
    lines = [
        "<!-- Generated by scripts/render_arci_public_table.py; synthetic evidence only. -->",
        "| ARCI synthetic sensitivity metric | Accepted value |",
        "| --- | ---: |",
    ]
    lines.extend(f"| {label} | {value} |" for label, value in rows)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.source.read_text(encoding="utf-8"))
    rendered = render_table(payload)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
